version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: app-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=apinest
      - MONGO_INITDB_ROOT_PASSWORD=123456