version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: app-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=apinest
      - MONGO_INITDB_ROOT_PASSWORD=123456

  mysql:
    image: mysql:5.6.42
    container_name: app-mysql
    volumes:
        - "./.docker/mysql:/var/lib/mysql"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=123456